name: Nindle Scraper

on:
  # Triggers the workflow every two days
  schedule:
    - cron: "0 0,12 * * *"
    
env:
  ELBERTS_TECH_SECRET: ${{ secrets.ELBERTS_TECH_SECRET }}
  NOTION_DB : ${{ secrets.NOTION_DB }}

jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run start
